# Generated by Django 4.1.7 on 2023-04-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="reacts",
            options={"default_permissions": ()},
        ),
    ]
