# Generated by Django 4.1.7 on 2023-04-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_alter_comments_options_alter_reacts_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comments",
            options={"default_permissions": []},
        ),
        migrations.AlterModelOptions(
            name="reacts",
            options={"default_permissions": []},
        ),
    ]
