# Generated by Django 4.1.7 on 2023-03-25 01:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0002_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=models.TextField(),
        ),
    ]
