# Generated by Django 4.1.7 on 2023-04-14 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_reacts'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statistical',
            table='statistical',
        ),
    ]
