# Generated by Django 4.1.7 on 2023-03-27 11:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0003_alter_blog_body_alter_blog_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
