# Generated by Django 4.1.7 on 2023-04-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_statistical_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='statistical',
            table=None,
        ),
    ]
