# Generated by Django 4.1.7 on 2023-03-27 12:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0004_alter_blog_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
