# Generated by Django 4.1.7 on 2023-04-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_blog_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Statisticals',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('view_my_posts', 'Can view your posts')]},
        ),
    ]
